/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import Institucion.INstitucion;
import datos.*;
import alumnos.*;
import modelo.*;

/**
 * @version 0.0.0,22/04/2016
 * @author Eduard QF
 */
public class PrincipalWindows extends javax.swing.JFrame {

    /**
     * objeto que almacenara la instanciacion del parametro bd entregado en el
     * constructor.
     */
    Body bd;

    /**
     * objeto de tipo INstitucion que almacenara el Ojeto institucion entregada
     * desde el metodo asignInst de bd.
     */
    INstitucion in;

    /**
     * matriz que almacena los datos de los alumnos como: nombre, apellido, Rut.
     */
    String[][] alumn;

    /**
     * constructor de la clase PrincipalWindows.
     *
     * @param bd permite acceso al objeto de tipo Body ya creado al hacer
     * agregarcelo a un atributo local.
     */
    public PrincipalWindows(Body bd) {
        this.bd = bd;
        in = bd.asignInst();
        alumn = new String[33][3];
        initComponents();
        rellenarTablero();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jMenu1 = new javax.swing.JMenu();
        jComboCurso = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuAsistencia = new javax.swing.JMenu();
        jMenuAnotaciones = new javax.swing.JMenuItem();
        jMenuEvaluacion = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItemReporteApoderado = new javax.swing.JMenuItem();
        jMenuItemAsistencia = new javax.swing.JMenuItem();
        jMenuItemReprobados = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemLenguaje = new javax.swing.JMenuItem();
        jMenuItemMatematica = new javax.swing.JMenuItem();
        jMenuItemHistoria = new javax.swing.JMenuItem();
        jMenuItemCiencias = new javax.swing.JMenuItem();
        jMenuItemIngles = new javax.swing.JMenuItem();

        jButton1.setText("jButton1");

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 A", "1 B","2 A", "2 B","3 A", "3 B","4 A", "4 B","5 A", "5 B","6 A", "6 B", "7 A", "7 B","8 A", "8 B" }));
        jComboCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboCursoActionPerformed(evt);
            }
        });

        jLabel1.setText("Curso:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            alumn,
            new String [] {
                "Nombre", "Apellido", "Rut"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jMenuAsistencia.setText("Alumnos");

        jMenuAnotaciones.setText("Anotaciones");
        jMenuAnotaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAnotacionesActionPerformed(evt);
            }
        });
        jMenuAsistencia.add(jMenuAnotaciones);

        jMenuEvaluacion.setText("Evaluaciones");
        jMenuEvaluacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEvaluacionActionPerformed(evt);
            }
        });
        jMenuAsistencia.add(jMenuEvaluacion);

        jMenuItem3.setText("Asistencia");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenuAsistencia.add(jMenuItem3);

        jMenuBar1.add(jMenuAsistencia);

        jMenu3.setText("Planificacion");
        jMenuBar1.add(jMenu3);

        jMenu5.setText("Generar Reporte");

        jMenuItemReporteApoderado.setText("Informe Apoderados");
        jMenuItemReporteApoderado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemReporteApoderadoActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItemReporteApoderado);

        jMenuItemAsistencia.setText("Informe Asistencia");
        jMenu5.add(jMenuItemAsistencia);

        jMenuItemReprobados.setText("Informe Reprobados");
        jMenu5.add(jMenuItemReprobados);

        jMenu2.setText("Informe Asignatura");

        jMenuItemLenguaje.setText("Lenguaje");
        jMenuItemLenguaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLenguajeActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemLenguaje);

        jMenuItemMatematica.setText("Matematica");
        jMenuItemMatematica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMatematicaActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemMatematica);

        jMenuItemHistoria.setText("Historia");
        jMenuItemHistoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemHistoriaActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemHistoria);

        jMenuItemCiencias.setText("Ciencias Naturales");
        jMenuItemCiencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCienciasActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemCiencias);

        jMenuItemIngles.setText("Ingles");
        jMenuItemIngles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemInglesActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemIngles);

        jMenu5.add(jMenu2);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * metodo de accion del JComboBox llamado jComboCurso y que llama al metodo
     * rellenarTablero de la misma clase.
     *
     * @param evt evento obtenido del JComboBox al ser seleccionado por
     * pantalla.
     */
    private void jComboCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboCursoActionPerformed
        rellenarTablero();

    }//GEN-LAST:event_jComboCursoActionPerformed

    /**
     * metodo que llena el jTable1 con los daros de los alumnos del curso
     * ingresado por el jComboCurso.
     */
    private void rellenarTablero() {
        String nombre[];
        alumn = new String[3][in.getCursos().get(jComboCurso.getSelectedIndex()).getAlumnos().size()];
        System.out.println(jComboCurso.getSelectedIndex());
        for (int i = 0; i < in.getCursos().get(jComboCurso.getSelectedIndex()).getAlumnos().size(); i++) {
            nombre = in.getCursos().get(jComboCurso.getSelectedIndex()).getAlumnos().get(i).getNombre().split(" ");
            System.out.println("nombre[0]: " + nombre[0]);
            jTable1.setValueAt(nombre[0], i, 0);
            jTable1.setValueAt(nombre[1], i, 1);
            jTable1.setValueAt(in.getCursos().get(jComboCurso.getSelectedIndex()).getAlumnos().get(i).getRut(), i, 2);
        }
    }

    /**
     * metodo encargado de instanciar y llamar el objeto VentanaAnotaciones.
     *
     * @param evt evento obtenido del boton jMenuAnotaciones;
     */
    private void jMenuAnotacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAnotacionesActionPerformed
        VentanaAnotacion va = new VentanaAnotacion(bd);
        va.setVisible(true);

    }//GEN-LAST:event_jMenuAnotacionesActionPerformed

    /**
     * metodo encargado de instanciar y llamar el objeto VentanaEvaluaciones.
     *
     * @param evt evento obtenido del boton jMenuEvaluacion.
     */
    private void jMenuEvaluacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEvaluacionActionPerformed
        VentanaEvaluaciones2 ve = new VentanaEvaluaciones2(bd);
        ve.setVisible(true);
    }//GEN-LAST:event_jMenuEvaluacionActionPerformed

    /**
     * metodo encargado de instanciar y llamra el objeto VentanaAsistencia.
     *
     * @param evt evento obtenido del boton jMenuItem3.
     */
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        VentanaAsistencia vasis = new VentanaAsistencia(bd);
        vasis.setVisible(true);

    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * metodo encargado de llamar al metodo generarReporte ubicado en Body,
     * entregandole el curso pertinenete.
     *
     * @param evt evento obtenido del boton jMenuItemReporteApoderado.
     */
    private void jMenuItemReporteApoderadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemReporteApoderadoActionPerformed
        bd.generarReporte(jComboCurso.getSelectedIndex());

    }//GEN-LAST:event_jMenuItemReporteApoderadoActionPerformed

    /**
     * metodo que llama al generador de reportes en Body con el parametro del
     * curso y la Asignatura que en este caso es Lenguaje.
     *
     * @param evt evento generado por el boton jMenuItemLenguaje.
     */
    private void jMenuItemLenguajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLenguajeActionPerformed
        bd.generarReporteNotasAsignaturas(jComboCurso.getSelectedIndex(), "Lenguaje");
    }//GEN-LAST:event_jMenuItemLenguajeActionPerformed

    /**
     * metodo que llama al generador de reportes en Body con el parametro del
     * curso y la Asignatura que en este caso es Ingles.
     *
     * @param evt evento generado por el boton jMenuItemMatematica.
     */
    private void jMenuItemMatematicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMatematicaActionPerformed
        bd.generarReporteNotasAsignaturas(jComboCurso.getSelectedIndex(), "Matematica");
    }//GEN-LAST:event_jMenuItemMatematicaActionPerformed

    /**
     * metodo que llama al generador de reportes en Body con el parametro del
     * curso y la Asignatura que en este caso es Historia.
     *
     * @param evt evento generado por el boton jMenuItemHistoria.
     */
    private void jMenuItemHistoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHistoriaActionPerformed
        bd.generarReporteNotasAsignaturas(jComboCurso.getSelectedIndex(), "Historia");
    }//GEN-LAST:event_jMenuItemHistoriaActionPerformed

    /**
     * metodo que llama al generador de reportes en Body con el parametro del
     * curso y la Asignatura que en este caso es Ingles.
     *
     * @param evt evento generado por el boton jMenuItemIngles.
     */
    private void jMenuItemInglesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemInglesActionPerformed
        bd.generarReporteNotasAsignaturas(jComboCurso.getSelectedIndex(), "Ingles");
    }//GEN-LAST:event_jMenuItemInglesActionPerformed

    /**
     * metodo que llama al generador de reportes en Body con el parametro del
     * curso y la Asignatura que en este caso es Ciencias.
     *
     * @param evt evento generado por el boton jMenuItemCiencias.
     */
    private void jMenuItemCienciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCienciasActionPerformed
        bd.generarReporteNotasAsignaturas(jComboCurso.getSelectedIndex(), "Ciencias");
    }//GEN-LAST:event_jMenuItemCienciasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboCurso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuItem jMenuAnotaciones;
    private javax.swing.JMenu jMenuAsistencia;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuEvaluacion;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItemAsistencia;
    private javax.swing.JMenuItem jMenuItemCiencias;
    private javax.swing.JMenuItem jMenuItemHistoria;
    private javax.swing.JMenuItem jMenuItemIngles;
    private javax.swing.JMenuItem jMenuItemLenguaje;
    private javax.swing.JMenuItem jMenuItemMatematica;
    private javax.swing.JMenuItem jMenuItemReporteApoderado;
    private javax.swing.JMenuItem jMenuItemReprobados;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
