package vistas;

import modelo.Body;

/**
 * @version 0.0.0, 23/04/2017
 * @author Eduard QF
 */
public class VentanaEvaluaciones2 extends javax.swing.JFrame {

    /**
     * atributo que almacenara la instanciacion del objeto Body resivida en el
     * constructor.
     */
    Body bd;

    /**
     * atributo que almacenara la instanciacion del objeto Institucion recivida
     * desde un metodo de bd.
     */
    Institucion.INstitucion in;

    /**
     * atributo que almacenara el arreglos de notas del curso con el que se
     * inicia el objeto VentanaEvaluaciones2.
     */
    String notas[][];

    /**
     * atributo que almacenara el titulo de las columnas del Jtable.
     */
    String[] title;

    /**
     * Constructor de la clase VentanaEvaluaciones.La Clase se llama
     * VentanaEvaluaciones2 por el echo de que su versión predecesora se
     * autodestruyo.
     *
     * @param bd que entrega la instanciacion ya echa del objeto Body.
     */
    public VentanaEvaluaciones2(Body bd) {
        this.bd = bd;
        in = bd.asignInst();
        llenarTable();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxCurso = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxAsignatura = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBoxCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 A", "1 B","2 A", "2 B","3 A", "3 B","4 A", "4 B","5 A", "5 B","6 A", "6 B", "7 A", "7 B","8 A", "8 B", }));
        jComboBoxCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCursoActionPerformed(evt);
            }
        });

        jLabel1.setText("Curso:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            notas,
            title
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("Asignatura:");

        jComboBoxAsignatura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lenguaje", "Matematica", "Historia", "Ciencias Naturales","Ingles" }));
        jComboBoxAsignatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAsignaturaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * metodo que se ejecuta al accionar el jComboBox de Curso y llama al metodo
     * rellenarTable.
     *
     * @param evt entrega el evento ocurrido en jComboBoxCurso.
     */
    private void jComboBoxCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCursoActionPerformed
        rellenarTable();
    }//GEN-LAST:event_jComboBoxCursoActionPerformed

    /**
     * metodo que se ejecuta al accionar el jComboBOx de Asignatura y llama al
     * metodo rellenarTable().
     *
     * @param evt entrega el evento ocurrido en jComboBoxAsignatura.
     */
    private void jComboBoxAsignaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAsignaturaActionPerformed
        rellenarTable();
    }//GEN-LAST:event_jComboBoxAsignaturaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxAsignatura;
    private javax.swing.JComboBox<String> jComboBoxCurso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    /**
     * metodo encargado de llenar los arreglos que tendran los datos iniciales
     * del jTable, estos se rellenan por default con los datos del curso 1 A y
     * Lenguaje como asignatura.
     */
    private void llenarTable() {
        notas = new String[in.getCursos().get(0).getAlumnos().size()][12];
        title = new String[12];
        title[0] = "Estudiantes";
        title[11] = "Promedio";
        int cont = 1;
        for (int i = 0; i < in.getCursos().get(0).getAlumnos().size(); i++) {
            notas[i][0] = in.getCursos().get(0).getAlumnos().get(i).getNombre();

            System.out.print("notas[i][0]: " + notas[i][0] + "\n");
            for (int j = 1; j < in.getCursos().get(0).getAsignatura().size(); j++) {
                for (int k = 0; k < in.getCursos().get(0).getAlumnos().get(i).getNotasEvaluaciones().size(); k++) {
                    if (in.getCursos().get(0).getAlumnos().get(i).getNotasEvaluaciones().get(k).getMateria().equalsIgnoreCase("Lenguaje")) {
                        System.out.println(String.valueOf(in.getCursos().get(0).getAlumnos().get(i).getNotasEvaluaciones().get(k).getNota()));
                        title[cont] = String.valueOf(in.getCursos().get(0).getAlumnos().get(i).getNotasEvaluaciones().get(k).getNumEvaluacion());
                        notas[i][cont] = String.valueOf(in.getCursos().get(0).getAlumnos().get(i).getNotasEvaluaciones().get(k).getNota());
                        cont++;
                    }
                }
                cont = 1;
            }

        }
    }

    /**
     * metodo que modifica los datos que contiene el jTable, segun los index de
     * los jComboBox curso y asignatura.
     */
    private void rellenarTable() {
        int cont = 1;
        for (int i = 0; i < in.getCursos().get(jComboBoxCurso.getSelectedIndex()).getAlumnos().size(); i++) {
            //notas[i][0] = in.getCursos().get(0).getAlumnos().get(i).getNombre();
            jTable1.setValueAt(in.getCursos().get(jComboBoxCurso.getSelectedIndex()).getAlumnos().get(i).getNombre(), i, 0);
            System.out.print("notas[i][0]: " + notas[i][jComboBoxCurso.getSelectedIndex()] + "\n");
            for (int j = 1; j < in.getCursos().get(jComboBoxCurso.getSelectedIndex()).getAsignatura().size(); j++) {
                for (int k = 0; k < in.getCursos().get(jComboBoxCurso.getSelectedIndex()).getAlumnos().get(i).getNotasEvaluaciones().size(); k++) {
                    if (in.getCursos().get(jComboBoxCurso.getSelectedIndex()).getAlumnos().get(i).getNotasEvaluaciones().get(k).getMateria().equalsIgnoreCase(String.valueOf(jComboBoxAsignatura.getSelectedItem()))) {
                        //notas[i][cont] = String.valueOf(in.getCursos().get(0).getAlumnos().get(i).getNotasEvaluaciones().get(k).getNota());
                        jTable1.setValueAt(in.getCursos().get(jComboBoxCurso.getSelectedIndex()).getAlumnos().get(i).getNotasEvaluaciones().get(k).getNota(), i, cont);
                        cont++;
                    }
                }
                cont = 1;
            }

        }
    }
}
